name: Regenerate Python Library
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d
      - name: Set release name as environment variable
        run: echo "RELEASE_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Delete folder
        run: |
          rm -rf meraki
      - name: Regenerate Python Library
        run: |
          python generator/generate_library.py -g true -v $RELEASE_NAME
      - name: Commit changes to new branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: support@meraki.com
          message: Automatically regenerated library.
          new_branch: release
